[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable optimizer and set the number of runs
optimizer = true
optimizer_runs = 200

# Specify the Solidity compiler version
solc_version = "0.8.25"
evm_version = "cancun"

[etherscan]
sonic = { key = "$SONIC_ETHERSCAN_KEY", chain = "57054", url = "https://api-testnet.sonicscan.org/api" }